# frps日志文件
frps_log: ./log/frps.log

# 输出日志目录
logs: ./tlog/

# frps 名字端口对应配置
name_port:
  "ZNGW": 3389

# 启用防火墙类型 iptables / firewall / md (Microsoft Defender)
tables_type: firewall

# ip白名单:
allow_ip:
  - 127.0.0.1

# 端口白名单
allow_port:
  - 80
  - 443

# 规则访问
rules:

  # 按数组顺序来，匹配到了就按匹配的规则执行，跳过此规则。
  # 地区以 http://ip-api.com/json/?lang=zh-CN 查询的结果为准
  # 端口: -1 所有端口
  # time: 时间区间
  # count: 访问次数，-1不限，0限制。其他为 time时间内访问count次，超出频率就限制

  - # 中国上海IP允许
    port: -1
    country: 中国
    regionName: 上海
    city: 上海
    time: 1
    count: -1

  - # 中国地区IP跳过地域判断
    port: -1
    country: 中国
    regionName:
    city:
    time: 600
    count: 3

  - # 其他地区IP禁止
    port: -1
    country:
    regionName:
    city:
    time: 1
    count: 0