# frps日志文件
frps_log: /var/log/frp/frps.log

# 输出日志目录
logs: ./log/

# frps 名字端口对应配置
name_port:
  "ssh-home": 6001
  "ssh-office": 6002

# 启用防火墙类型 iptables / firewall / md (Microsoft Defender)
tables_type: iptables

# ip白名单:
allow_ip:
  - 127.0.0.1

# 规则访问
rules:

  # 按数组顺序来，匹配到了就按匹配的规则执行，跳过此规则。
  # port: -1 所有端口
  # country: 国家代码
  # time: 时间区间
  # count: 访问次数，-1不限，0限制。其他为 time时间内访问count次，超出频率就限制

  - # 中国地区IP 10分钟3次
    port: -1
    country: CN
    time: 10
    count: 3

  - # 其他地区IP禁止
    port: -1
    country:
    time: 1
    count: 1
